---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Madoka.
--- DateTime: 2025/8/16 18:58
---
-- 优惠券ID
local voucherId = ARGV[1]
-- 用户ID
local userId = ARGV[2]
-- 订单ID
local orderId = ARGV[3]
-- 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单ID
local orderKey = 'seckill:order:' .. voucherId

if (tonumber(redis.call('get', stockKey)) <= 0) then
-- 库存不足返回1
    return 1
end

if (redis.call('sismember', orderKey, userId) == 1) then
    -- 存在返回2
    return 2
end

redis.call('incrby', stockKey, - 1)
redis.call('sadd', orderKey, userId)
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0